### ISSUE TITLE
SN API v004

### ISSUE THREAD

**Issue by pyrox0** [jonhadfield/sn-dotfiles#10]
Could you update this so that it works with SN API v004? I would love to help, but I am not comfortable with Go. Thanks!

**Comment by jonhadfield** [comment]
Actively working on it now. I'll let you know when ready to test.

**Comment by jonhadfield** [comment]
I've just put out a very early release for testing: https://github.com/jonhadfield/sn-dotfiles/releases/tag/0.1.0
Please make sure you have a backup first and let me know if you spot any issues.
